# list1 = [1, 2, 3, "你好", "你大爷"]
# print(type(list1))
# print(len(list1))
# print(list1)
# print(list1[1:3])
# print(list1[::-1])
# print(list1 * 5)
# print("增加")
# print("追加之前", list1)
# list1.append(["追加1", "追加2", 43132])
# print("追加之后", list1)
# rsData = list(range(10))
# list1.extend(rsData)
# print('extend之后',list1)
# list1[5][1]=99.9
# print('修改之后',list1)
listA = list(range(10, 50, 2))
print(listA)
listA.remove(16)
print(listA)
listA.pop(0)
print(listA)
print(listA.index(20))
print(listA.index(20, 2, 15))
